services:
  backend:
    image: tqa-backend 
    build: 
      context: ./backend 
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    networks:
      - tqa 

  frontend:
    image: tqa-frontend
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    ports:
      - "5173:5173"
    depends_on:
      - tqa-mysql
    networks:
      - tqa  
  
  tqa-mysql:
    image: mysql
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5 
    volumes:
      - mysql-data:/var/lib/mysql
    


volumes:
  mysql-data:
networks:
  tqa: 