import os
import sys
import json
import asyncio
import argparse
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent / "backend"
sys.path.insert(0, str(BACKEND_DIR))

from dotenv import load_dotenv
load_dotenv(BACKEND_DIR / ".env")

from langchain_openai import OpenAIEmbeddings
from openai import OpenAI
from ragas import evaluate, EvaluationDataset
from ragas.dataset_schema import SingleTurnSample
from ragas.metrics._faithfulness import faithfulness
from ragas.metrics._answer_relevance import answer_relevancy
from ragas.llms import llm_factory
from ragas.embeddings import LangchainEmbeddingsWrapper

# The eval drives the real pipeline instead of reimplementing it, so the rewrite
# and classify steps are measured too and the prompt cannot drift out of sync.
from helpers.ingest import ingest_transcript
from helpers.store import transcripts
from rag import query_stream

EVAL_USER = "eval@localhost"


def load_pairs(jsonl_path: str) -> list[dict]:
    pairs = []
    with open(jsonl_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                pairs.append(json.loads(line))
    return pairs


async def answer_question(question: str) -> str:
    tokens = []
    async for kind, content in query_stream(question, EVAL_USER, []):
        if kind == "token":
            tokens.append(content)
    return "".join(tokens)


def main():
    parser = argparse.ArgumentParser(description="Run RAGAS evaluation on the TQA pipeline.")
    parser.add_argument("--pdf", required=True, help="Path to the transcript PDF to evaluate against.")
    parser.add_argument(
        "--pairs",
        default=str(Path(__file__).parent / "prompt_pairs.jsonl"),
        help="Path to a JSONL file generated by generate_pairs.py (default: testing/prompt_pairs.jsonl).",
    )
    parser.add_argument(
        "--output",
        default=str(Path(__file__).parent / "results.json"),
        help="Where to write scores (default: testing/results.json).",
    )
    args = parser.parse_args()

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OPENAI_API_KEY is not set. Add it to backend/.env or export it.")

    pdf_path = Path(args.pdf)
    if not pdf_path.exists():
        raise FileNotFoundError(f"Transcript PDF not found at '{pdf_path}'")

    print(f"[eval] Ingesting transcript: {pdf_path.name}")
    transcript_text = ingest_transcript(str(pdf_path))
    transcripts[EVAL_USER] = transcript_text
    print(f"[eval] Context is {len(transcript_text)} chars, sent in full with every question")

    openai_client = OpenAI(api_key=api_key)
    ragas_llm = llm_factory("gpt-4o-mini", client=openai_client)
    ragas_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(api_key=api_key, model="text-embedding-3-large"))

    faithfulness.llm = ragas_llm
    answer_relevancy.llm = ragas_llm
    answer_relevancy.embeddings = ragas_embeddings

    entries = load_pairs(args.pairs)
    print(f"[eval] Loaded {len(entries)} questions from {args.pairs}")
    print(f"[eval] Running {len(entries)} questions through the pipeline...")

    samples = []
    for entry in entries:
        q = entry["question"]
        print(f"  -> {q}")
        answer = asyncio.run(answer_question(q))
        samples.append(SingleTurnSample(
            user_input=q,
            response=answer,
            retrieved_contexts=[transcript_text],
        ))

    dataset = EvaluationDataset(samples=samples)
    metrics = [faithfulness, answer_relevancy]

    metric_names = [type(m).__name__ for m in metrics]
    print(f"\n[eval] Running RAGAS (metrics: {metric_names})...")

    results = evaluate(dataset, metrics=metrics)

    df = results.to_pandas()
    scores = {m.name: float(df[m.name].mean()) for m in metrics if m.name in df.columns}

    print("\n=== RAGAS Results ===")
    for metric, score in scores.items():
        print(f"  {metric}: {score:.4f}")

    # Keep the per-question rows so low scores can be traced to the answer that
    # caused them. The transcript context is dropped — it is identical per row.
    rows = [
        {
            "question": r["user_input"],
            "answer": r["response"],
            **{m.name: (None if r[m.name] != r[m.name] else float(r[m.name]))
               for m in metrics if m.name in df.columns},
        }
        for r in df.to_dict("records")
    ]

    out_path = Path(args.output)
    with open(out_path, "w") as f:
        json.dump({"pdf": pdf_path.name, "metrics": scores, "rows": rows}, f, indent=2)
    print(f"\n[eval] Results saved to {out_path}")


if __name__ == "__main__":
    main()
