import os
import sys
import json
import argparse
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent / "backend"
sys.path.insert(0, str(BACKEND_DIR))

from dotenv import load_dotenv
load_dotenv(BACKEND_DIR / ".env")

from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from openai import OpenAI
from ragas import evaluate, EvaluationDataset
from ragas.dataset_schema import SingleTurnSample
from ragas.metrics._faithfulness import faithfulness
from ragas.metrics._answer_relevance import answer_relevancy
from ragas.llms import llm_factory
from ragas.embeddings import LangchainEmbeddingsWrapper


def load_pairs(jsonl_path: str) -> list[dict]:
    pairs = []
    with open(jsonl_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                pairs.append(json.loads(line))
    return pairs


PROMPT_TEMPLATE = PromptTemplate.from_template("""
You are a helpful assistant that answers questions about a student's academic transcript. \
Use only the context provided to answer. Answer directly as if you were talking to a real student. \
Start with the answer and be concise. \
Answer in 1-2 sentences maximum. \
If the answer is not in the context, say you don't know.

Context:
{context}

Question: {question}

Answer:""")


def load_index(index_key: str, index_dir: str, api_key: str) -> FAISS:
    embeddings = OpenAIEmbeddings(api_key=api_key, model="text-embedding-3-large")
    index_path = os.path.join(index_dir, f"faiss_index_{index_key}")

    if not os.path.exists(index_path):
        raise FileNotFoundError(
            f"No FAISS index found at '{index_path}'.\n"
            f"Upload a document through the app first so the index is generated."
        )

    return FAISS.load_local(index_path, embeddings, allow_dangerous_deserialization=True)


def retrieve_and_answer(question: str, vector_store: FAISS, llm: ChatOpenAI) -> tuple[str, list[str]]:
    retriever = vector_store.as_retriever(search_kwargs={"k": 5})

    retrieved_docs = retriever.invoke(question)
    contexts = [doc.page_content for doc in retrieved_docs]

    chain = (
        {"context": retriever, "question": RunnablePassthrough()}
        | PROMPT_TEMPLATE
        | llm
        | StrOutputParser()
    )

    answer = chain.invoke(question)
    return answer, contexts


def main():
    parser = argparse.ArgumentParser(description="Run RAGAS evaluation on the TQA pipeline.")
    parser.add_argument("--index_key", type=str, required=True, help="Index key in the format <email>_<filename>")
    parser.add_argument(
        "--index_dir",
        default=str(BACKEND_DIR / "data"),
        help="Directory containing FAISS indexes (default: backend/data)",
    )
    parser.add_argument(
        "--pairs",
        default=str(Path(__file__).parent / "prompt_pairs.jsonl"),
        help="Path to a JSONL file generated by generate_pairs.py (default: testing/prompt_pairs.jsonl).",
    )
    args = parser.parse_args()

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OPENAI_API_KEY is not set. Add it to backend/.env or export it.")

    print(f"[eval] Loading FAISS index for {args.index_key}...")
    
    vector_store = load_index(args.index_key, args.index_dir, api_key)
    llm = ChatOpenAI(api_key=api_key, model="gpt-4o-mini", temperature=0)
    openai_client = OpenAI(api_key=api_key)
    ragas_llm = llm_factory("gpt-4o-mini", client=openai_client)
    ragas_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(api_key=api_key, model="text-embedding-3-large"))

    faithfulness.llm = ragas_llm
    answer_relevancy.llm = ragas_llm
    answer_relevancy.embeddings = ragas_embeddings

    raw = load_pairs(args.pairs)
    entries = [{"question": p["question"], "chunk": p["chunk"]} for p in raw]
    print(f"[eval] Loaded {len(entries)} questions from {args.pairs}")

    print(f"[eval] Running {len(entries)} questions through the pipeline...")

    samples = []
    for entry in entries:
        q = entry["question"]
        print(f"  -> {q}")
        answer, ctx = retrieve_and_answer(q, vector_store, llm)
        samples.append(SingleTurnSample(
            user_input=q,
            response=answer,
            retrieved_contexts=ctx,
        ))

    dataset = EvaluationDataset(samples=samples)
    metrics = [faithfulness, answer_relevancy]

    metric_names = [type(m).__name__ for m in metrics]
    print(f"\n[eval] Running RAGAS (metrics: {metric_names})...")

    results = evaluate(dataset, metrics=metrics)

    df = results.to_pandas()
    scores = {m.name: float(df[m.name].mean()) for m in metrics if m.name in df.columns}

    print("\n=== RAGAS Results ===")
    for metric, score in scores.items():
        print(f"  {metric}: {score:.4f}")


    out_path = Path(__file__).parent / "results.json"
    with open(out_path, "w") as f:
        json.dump({"index_key": args.index_key, "metrics": scores}, f, indent=2)
    print(f"\n[eval] Results saved to {out_path}")


if __name__ == "__main__":
    main()
